[[constraint]]
  branch = "master"
  name = "github.com/kolo/xmlrpc"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[prune]
  go-tests = true
  unused-packages = true
